Feature/lvnod 58 avatar
igorkokotko/emOcean pull request #13
Opened 2019-11-17 23:21 UTC by Oksana-Z

2019-11-18 18:21 UTC, de5peratelighter commented on client/src/components/Avatar.vue
> +  <div>
No need to add ext

2019-11-18 18:24 UTC, de5peratelighter requested changes

2019-11-18 18:24 UTC, de5peratelighter commented on client/src/components/Avatar.vue
> +  <div>
No need to add extra div - this can bring complications later on.
Custom components can always be component wrappers (start with custom component)

2019-11-18 21:02 UTC, igorkokotko requested changes

2019-11-18 21:02 UTC, igorkokotko commented on client/src/components/Avatar.vue
> +      default: ''
Please use require property, avatar component should alway have img.

2019-11-19 08:49 UTC, igorkokotko approved these changes

2019-11-19 08:49 UTC, merged