Feature/editor photos
igorkokotko/emOcean pull request #33
Opened 2019-12-03 21:32 UTC by Oksana-Z

2019-12-05 10:11 UTC, Oksana-Z commented
code:
-logout
-changed profile.js(vuex)
-implemented editing images (vue-cropper.js)
-created component EditImage.vue
-added notifications in Edit profile page
-added styles, quasar componenents in Edit profile page
-Edit profile page communicates with backend throw Vuex

2019-12-05 17:44 UTC, igorkokotko commented
@Oksana-Z please resolve conflicts

2019-12-08 15:33 UTC, igorkokotko requested changes

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +          <template v-if="photoUrl===''">
I'm a bit confused why you check if photoUrl equals to empty string and inside that block you pass to avatar component :img  which is empty string.

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +          <template v-if="backgroundUrl===''">
The same here, please explain why do you really need such weird behavior?

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +              :aspectRatio="16 / 9"
Don't use magic numbers. Store them in data.

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +      return this.$store.getters['profile/myProfile']
Please use getters like this -  https://vuex.vuejs.org/ru/guide/getters.html#%D0%B2%D1%81%D0%BF%D0%BE%D0%BC%D0%BE%D0%B3%D0%B0%D1%82%D0%B5n%D1%8C%D0%BD%D0%B0%D1%8F-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F-mapgetters

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +    this.$store.dispatch('profile/getMyProfile')
Use mapActions.

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +      if (val.target.files[0].size > 2097152) {
Don't use magic numbers. Declare intuitive variable why you need exactly this number value.

2019-12-08 15:33 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditProfile/index.vue
> +      if (val.target.files[0].size > 2097152) {
You have almost identical method - uploadPhotoUrl, does it make sense to reuse it?

2019-12-08 15:33 UTC, igorkokotko commented on client/src/App.vue
> +    if (window.localStorage.getItem('token') && window.localStorage.getItem('token') !== '') {
Please reuse - https://github.com/igorkokotko/emOcean/blob/develop/client/src/views/Authentication/Authorized.js#L2

2019-12-09 10:47 UTC, igorkokotko approved these changes

2019-12-09 10:47 UTC, merged