Followers page
igorkokotko/emOcean pull request #34
Opened 2019-12-04 21:40 UTC by KhrystynaKorinetska

2019-12-05 10:29 UTC, de5peratelighter requested changes

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/FollowList/FollowItem.vue
> +      v-for="followItem in follow"
Try to stick to KISS naming
Please rename "followItem" to "item" (seeing large names may look like there is some kind of data/computed while this is only iteration item). Also "follow" is a terrible name for array/list - verbs are used for "action/event" names

p.s: Btw in case of having list inside another list - parent iteration item still would be "item" while sublist would be "subItem"

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/FollowList/FollowItem.vue
> +  <q-list class="follow-list">
I don't get why this component is called _FollowItem_ while its actually a kind of a LIST

I'd suggest moving:
_q-list > follow-item v-for_
 to parent _FollowList_ component
While current (FollowItem) will start directly from q-item.

If iterated component is quite large (as in our case) - it's always a separate component - it's ok if it starts with some library components, making iterated component into a separate component makes them easy to update and target.

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/FollowList/FollowItem.vue
> +  .follow-list {
Since this is a global stylings - move them to global scss file

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/FollowList/index.vue
> +      tab: this.$route.query.p
PLEASE don't ever use "this" inside a "data".
"tab" in our cases is 100% a computed

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/FollowList/index.vue
> +  computed: mapGetters(['followingGetter', 'followersGetter']),
Please follow proper ordering convention(makes this easy to read/navigate through):
props > data > computed > lifecycle callbacks > methods

2019-12-05 10:29 UTC, de5peratelighter commented on client/src/views/Profile/index.vue
> +    // this.getUser(2)
Please remove unneeded code

2019-12-08 15:37 UTC, igorkokotko requested changes

2019-12-08 15:37 UTC, igorkokotko commented on client/src/store/modules/profile.js
> +        id: 1,
Why you still using hardcoded values? Please remove all mocks and start to work with real data.

2019-12-08 15:37 UTC, igorkokotko commented on client/src/views/Profile/index.vue
> +    <div class="profile-header" :style="{ backgroundImage: `${(profileGetter.user_background) ? 'url('+profileGetter.user_background + ')' : 'url(https://i.ytimg.com/vi/DiS7ZMwTA0I/maxresdefault.jpg)
Please move to computed property.

2019-12-09 10:48 UTC, igorkokotko commented
@KhrystynaKorinetska please resolve conflicts

2019-12-10 13:35 UTC, de5peratelighter approved these changes

2019-12-10 19:46 UTC, igorkokotko approved these changes

2019-12-10 22:06 UTC, merged