Preferences db request/LVNOD-83
igorkokotko/emOcean pull request #35
Opened 2019-12-04 23:37 UTC by reshetniktati

saving preferences to db

2019-12-08 15:40 UTC, igorkokotko requested changes

2019-12-08 15:40 UTC, igorkokotko commented on client/src/views/Settings/Tabs/EditPreferences/index.vue
> +          alert('data saved')
Use alert/notification components rather than native alert.

2019-12-08 17:19 UTC, reshetniktati commented on client/src/views/Settings/Tabs/EditPreferences/index.vue
> +          alert('data saved')
done 
notification instead alerts

2019-12-09 10:50 UTC, igorkokotko approved these changes

2019-12-09 10:50 UTC, merged