Improved auth
igorkokotko/emOcean pull request #65
Opened 2019-12-21 13:56 UTC by orestkozolup

Changed the way of authorization status check. Adjusted header behaviour to the new method. Removed a file with the old check of authorization.

2019-12-21 17:40 UTC, igorkokotko requested changes

2019-12-21 17:40 UTC, igorkokotko commented on client/src/App.vue
> +      window.localStorage.getItem('token') !== ''
Why you remove isAuthorized? And why you need extra check for window.localStorage.getItem('token') !== ''?

2019-12-21 17:40 UTC, igorkokotko commented on client/src/layouts/Header.vue
> +    } catch (e) {
Catch should not be an empty block.

2019-12-24 13:11 UTC, igorkokotko requested changes

2019-12-24 13:11 UTC, igorkokotko commented on client/src/views/Authentication/AuthEmailAction.vue
> +        if (res === true) {
return res ? next('/feed') : next() would be shorter and you can remove finally block.

2019-12-24 13:11 UTC, igorkokotko commented on client/src/views/Authentication/AuthLogin.vue
> +        if (res === true) {
Please look comment above

2019-12-26 09:52 UTC, igorkokotko requested changes

2019-12-26 09:52 UTC, igorkokotko commented on client/src/services/Authorized.js
> +        if (res.data.id === window.localStorage.getItem('profileId')) {
res.data.id === window.localStorage.getItem('profileId') if this statement equal to true then you could resolve this result

2019-12-26 09:52 UTC, igorkokotko commented on client/src/views/Settings/index.vue
> +      .finally(() => {
Why you need finally?

2019-12-27 09:26 UTC, de5peratelighter approved these changes

2019-12-27 13:37 UTC, ghost reviewed
Molodec

2019-12-27 13:38 UTC, ghost approved these changes

2019-12-27 19:51 UTC, igorkokotko approved these changes

2019-12-27 19:51 UTC, merged